theme: "hugo-PaperMod"
baseURL: https://www.joshcheema.io
languageCode: en-us
title: joshcheema.io
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

menu:
  main:
    - name: Home
      url: https://www.joshcheema.io
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: CV
      url: /cv/
      weight: 3
    - name: GitHub
      url: https://github.com/josh-cheema
      weight: 4
    - name: LinkedIn
      url: https://www.linkedin.com/in/josh-cheema
      weight: 5

enableEmoji: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: production
  defaultTheme: auto
  
  ShowShareButtons: true
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true
  math: true
  comments: true

  homeInfoParams:
      Title: >
        Hello 👋
      Content: |
          Welcome to my personal blog and portfolio site. The aim of this site is to 
          showcase personal projects and help reinforce my understanding of general 
          programming, machine learning and data science topics via regular blog posts 
          \- and hopefully help other people too! 
          
          -
          
          If you spot any mistakes (there could be a few) please add a
          comment to the relevant post and I will try to correct as soon as possible. 
          
          -
          
          Please feel free to get in touch with me via LinkedIn or view my GitHub portfolio
          using the links provided.
          
  
  socialIcons:
        - name: github
          url: "https://github.com/josh-cheema"
        - name: linkedin
          url: "https://www.linkedin.com/in/josh-cheema"

markup:
  goldmark:
    renderer:
      unsafe: true
